# The toolbox will require this
# ---
# - hosts: localhost
#   name: Deploy the vLLM pod and benchmark whisper while gathering dcgm metrics and render some usage plots
#   gather_facts: no
#   roles:
#     - role: psap.topsail.tests
#       tasks_from: whisper

- hosts: localhost
  name: Deploy the vLLM pod and benchmark whisper while gathering dcgm metrics and render some usage plots
  gather_facts: no
  roles:
    - role: psap.topsail.smigather
      vars:
        collect_metrics_enabled: true
        stop_metrics_enabled: false

    - role: psap.topsail.whisper

    - role: psap.topsail.smigather
      vars:
        collect_metrics_enabled: false
        stop_metrics_enabled: true

    - role: psap.topsail.plotter
