# Build and push the docs website
name: Build docs

on:
  pull_request:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - name: Use checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install requirements
        run: |
          sudo apt update && sudo apt install graphviz
          python3 -m pip install -r ./psap/topsail/docs/requirements.txt

      - name: Install the collection
        run: |
          cd ./psap/topsail
          ansible-galaxy install -r requirements.yml --force
          rm -rf ~/.ansible/collections/ansible_collections/psap/topsail
          ansible-galaxy collection build -v --force --output-path releases/
          ansible-galaxy collection install --force --force-with-deps releases/psap-topsail-`cat galaxy.yml | shyaml get-value version`.tar.gz

      - name: Render the projects roles and inventory diagrams
        run: |
          set -x
          cd ./psap/topsail
          mkdir -p docs/_build/html/_sources/
          ansible-playbook-grapher --include-role-tasks \
                                   --renderer graphviz \
                                   playbook_whisper.yml \
                                   -o docs/_build/html/extending/playbook_whisper
          ansible-playbook-grapher --include-role-tasks \
                                   --renderer graphviz \
                                   playbook_plotter.yml \
                                   -o docs/_build/html/extending/playbook_plotter

          cat << EOF >> docs/extending/playbook_diagrams.rst

          playbook task whisper
          ~~~~~~~~~~~~~~~~~~~~~

          .. image:: /playbook_whisper.svg
            :width: 400
            :alt: Alternative text

          playbook task plotter
          ~~~~~~~~~~~~~~~~~~~~~

          .. image:: /playbook_plotter.svg
            :width: 400
            :alt: Alternative text

          EOF

      - name: Render the docs
        run: |
          cd ./psap/topsail/docs
          make html

      - uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: psap/topsail/docs/_build/html/
          if-no-files-found: error

      - name: Commit documentation changes
        run: |
          tmp_folder=$(mktemp -d /tmp/tmp.XXXXXXXXXX)
          cp -r ./psap/topsail/docs/_build/html/* $tmp_folder/
          rm -rf *; rm -rf .github
          git switch --orphan gh-pages
          cp -r $tmp_folder/* .
          touch .nojekyll
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update documentation" -a || true

      - name: Push changes
        if: github.event_name == 'push'
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
